server:
  port: 8081

spring:
  security:
    oauth2:
      client: ## prefix
        registration: ## 클라이언트 설정 (Map 속성)
#          keycloak: ## (Map의 키 값)
#            authorizationGrantType: authorization_code
#            clientId: oauth2-client-app
#            clientName: oauth2-client-app
#            clientSecret: zxMvv3yCjZVoEJFAUzNUdYlJgJla9yuf
#            clientAuthenticationMethod: client_secret_basic
#            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
#            scope: openid, profile

          google:
            client-id: 297586071592-qld2a4k62eucouleq2edokab0f7s7gn9.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email

          naver:
            authorization-grant-type: authorization_code
            client-id: DgOv9nXsx8v1oWQfw6Jy
            client-secret: J_F8G72aH9
            client-name: naver-client-app2
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile, email # naver는 openid 미제공

          kakao:
            authorization-grant-type: authorization_code
            client-id: 2ff36c75453548f9f6519f4e3d7da044 # REST API 키
            client-secret: NeHFx8PvBqQMsW5OSnHFomrWoe2G2rKE
            client-name: client-app
            client-authentication-method: POST #kakao는 POST
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            # scope: profile_nickname, profile_image, account_email # OAuth2.0
            scope: openid, profile_nickname, account_email # OIDC

        provider: ## : 공급자 설정 (Map 속성)
          naver: #네이버의 경우, 외부 서비스 이용자이므로 설정 필요
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao: #카카오의 경우, 외부 서비스 이용자이므로 설정 필요
            issuer-uri: https://kauth.kakao.com # issuer-uri 내 모든 메타데이터 존재하므로 이것만 있어도 됨
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me # OAuth2 방식
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id #default : id


  mvc:
    static-path-pattern: "/static/**" ## 정적 리소스 매핑 패턴 (기본 : 루트(/**)) 변경